### ISSUE TITLE
App Crashes on My Device

### ISSUE THREAD

**Issue by muhammadarif1** [ZoidbergZero/Canora-MusicPlayer#9] opened 2019-05-26 18:04 UTC
**Describe the bug**
I can't open the app to play music

**To Reproduce**
- install the app than open it and see error

**Expected behavior**
I expect i can use this app to play a music on my phone

**Smartphone:**
 - Device: [oppo neo5]
 - OS: [5.1]
 
**Additional context**
I still try to find a log cat to see cause error

**Comment by ZoidbergZero** [comment] 2019-05-27 09:46
What Version of Canora are you using? V0.41 Runs fine on Marhsmallow on my End.

Also Please dont Post Links to External Source in Issues Please, 
If you attach a Screenshot of the Problem use the File Upload provided by Github by simply dragging and dropping the File here.

Please supply a full Logcat File of the issue happening, so i can find out what the Problem is.

**Comment by muhammadarif1** [comment] 2019-05-27 18:09
android device oppo neo 5
os : android 6.1

```I/ActivityManager(  900): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=ch.swissproductions.canora/.MainActivity bnds=[128,302][239,431]} from uid 10064 from pid 31097 on display 0

D/FeatureProxyBase(  900): FeatureProxyBase class constructor

D/FeatureProxyBase(  900): getService(), serviceName = multiwindow_service_v1

D/Surface ( 1704): Surface::setBuffersDimensions(this=0xb45aa700,w=480,h=38)

V/WindowManager(  900): Changing focus from Window{16eb3534 u0 com.oppo.launcher/com.oppo.launcher.Launcher} to null Callers=com.android.server.wm.WindowManagerService.moveStackWindowsLocked:5788 com.android.server.wm.WindowManagerService.moveTaskToTop:5826 com.android.server.am.ActivityStack.moveToFront:570 com.android.server.am.ActivityStackSupervisor.startActivityUncheckedLocked:2516 

D/LockPatternUtils(  900): s=true ,L=true ,q=true ,v=false

D/KeyguardViewMediator(29576): setOccluded false

D/KeyguardViewMediator(29576): handleKeyguardVisibilityChanged mKeyguardViewManager = com.android.keyguard.KeyguardViewManager@f8d8da8

D/KeyguardViewManager(29576): handleKeyguardVisibilityChanged showing = true

D/FeatureProxyBase(  900): FeatureProxyBase class constructor

D/FeatureProxyBase(  900): getService(), serviceName = multiwindow_service_v1

I/WindowManager(  900): Losing focus: Window{16eb3534 u0 com.oppo.launcher/com.oppo.launcher.Launcher}

V/WindowManager(  900): addAppToken: AppWindowToken{1d8c2083 token=Token{f43bb32 ActivityRecord{3229673d u0 ch.swissproductions.canora/.MainActivity t439}}} to stack=1 task=439 at 0

I/libPerfService(  900): 1: set: 3

D/PowerManagerService(  900): acquireWakeLockInternal: lock=779984791, flags=0x1, tag="ActivityManager-Launch", ws=null, uid=1000, pid=900

D/PowerManagerService(  900): updateWakeLockSummaryLocked: mWakefulness=Awake, mWakeLockSummary=0x1

D/PowerManagerService(  900): updateUserActivitySummaryLocked: mWakefulness=Awake, mUserActivitySummary=0x1, nextTimeout=103401949 (in 1792839 ms)```

**Comment by ZoidbergZero** [comment] 2019-05-27 18:30
I clearly told you to not post Links to External Sources, please Attach the Logfile in a Comment here, otherwise i am not going to be able to help you.

**Comment by muhammadarif1** [comment] 2019-05-27 18:30
https://master.tus.io/files/f1ecb130e5681e56f31b4e1e79a6225b+6Df8gi6wFpLFu7G2.iNDNR3MuS.UT_Q9K1FiWIBGLYQAWF_IArUD4L1vjtc7IprJg1VBFaIehm59fn3KPQoB3KV98cI1KatOCWToBq0mQeLRZh0Vx0yFnD6vw5.2QVRc

**Comment by muhammadarif1** [comment] 2019-05-27 18:33
it realy big

```I/ActivityManager(  900): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=ch.swissproductions.canora/.MainActivity bnds=[128,302][239,431]} from uid 10064 from pid 31097 on display 0

D/FeatureProxyBase(  900): FeatureProxyBase class constructor

D/FeatureProxyBase(  900): getService(), serviceName = multiwindow_service_v1

I/MtpServer( 7711): operation: MTP_OPERATION_GET_OBJECT_PROP_LIST, 0x9805

I/MtpServer( 7711): got MTP_OPERATION_GET_OBJECT_PROP_LIST command MTP_OPERATION_GET_OBJECT_PROP_LIST, line 602 

I/MtpServer( 7711): GetObjectPropList handle: 0x10a51, format: NONE, property: MTP_PROPERTY_OBJECT_FORMAT, group: 0, depth: 0

D/MtpDatabase( 7711): getObjectPropertyList: handle = 0x10a51, property = 0xdc02

D/MtpPropertyGroup( 7711): createProperty: code = 0xdc02, type = 0x4

D/MtpPropertyGroup( 7711): getPropertyList handle: 10a51, format: 0, depth: 0

D/MtpPropertyGroup( 7711): getPropertyList handle: 0x10a51, depth: 0x0, don't query if not necessary!!

D/LockPatternUtils(  900): s=true ,L=true ,q=true ,v=false

D/KeyguardViewMediator(29576): setOccluded false

D/KeyguardViewMediator(29576): handleKeyguardVisibilityChanged mKeyguardViewManager = com.android.keyguard.KeyguardViewManager@f8d8da8

D/KeyguardViewManager(29576): handleKeyguardVisibilityChanged showing = true

D/FeatureProxyBase(  900): FeatureProxyBase class constructor

D/FeatureProxyBase(  900): getService(), serviceName = multiwindow_service_v1

D/MtpDatabase_JNI( 7711): virtual android::MtpResponseCode MyMtpDatabase::getObjectPropertyList(android::MtpObjectHandle, uint32_t, uint32_t, int, int, android::MtpDataPacket&): handle = 0x10a51, count = 1

D/MtpDatabase_JNI( 7711): virtual android::MtpResponseCode MyMtpDatabase::getObjectPropertyList(android::MtpObjectHandle, uint32_t, uint32_t, int, int, android::MtpDataPacket&) result: 0x2001 

I/MtpServer( 7711): sending data:

I/MtpServer( 7711): sending response 2001

E/MtpServer( 7711): MtpServer::run mFD: 48

V/WindowManager(  900): addAppToken: AppWindowToken{995ce55 token=Token{2a67150c ActivityRecord{3520f83f u0 ch.swissproductions.canora/.MainActivity t442}}} to stack=1 task=442 at 0

I/libPerfService(  900): 1: set: 3

D/PowerManagerService(  900): acquireWakeLockInternal: lock=779984791, flags=0x1, tag="ActivityManager-Launch", ws=null, uid=1000, pid=900

D/PowerManagerService(  900): updateWakeLockSummaryLocked: mWakefulness=Awake, mWakeLockSummary=0x1

D/PowerManagerService(  900): updateUserActivitySummaryLocked: mWakefulness=Awake, mUserActivitySummary=0x1, nextTimeout=103670418 (in 1792895 ms)

D/PowerManagerService(  900): mDisplayPowerRequest.policy = 3

D/PowerManagerService(  900): isWfdEnabled() mWfdStatus=WifiDisplayStatus{featureState=2, scanState=0, activeDisplayState=0, activeDisplay=null, displays=[], sessionInfo=WifiDisplaySessionInfo: C/O:Client,GId:,Pp:,SId:0,IP:}, return false

D/PowerManagerService(  900): updateDisplayPowerStateLocked: mDisplayReady=true, policy=3, mWakefulness=1, mWakeLockSummary=0x1, mUserActivitySummary=0x1, mBootCompleted=true, mScreenBrightnessBoostInProgress=false

D/FeatureProxyBase(  900): FeatureProxyBase class constructor

D/PowerManagerService(  900): Acquiring suspend blocker "PowerManagerService.WakeLocks".

D/FeatureProxyBase(  900): getService(), serviceName = multiwindow_service_v1

D/FeatureProxyBase(  900): FeatureProxyBase class constructor

D/FeatureProxyBase(  900): getService(), serviceName = multiwindow_service_v1

I/MtpServer( 7711): operation: MTP_OPERATION_GET_OBJECT_PROP_LIST, 0x9805

I/MtpServer( 7711): got MTP_OPERATION_GET_OBJECT_PROP_LIST command MTP_OPERATION_GET_OBJECT_PROP_LIST, line 602 

D/MtpDatabase( 7711): getObjectPropertyList: handle = 0x10a52, property = 0xdc02

I/MtpServer( 7711): GetObjectPropList handle: 0x10a52, format: NONE, property: MTP_PROPERTY_OBJECT_FORMAT, group: 0, depth: 0

D/MtpPropertyGroup( 7711): createProperty: code = 0xdc02, type = 0x4

D/MtpPropertyGroup( 7711): getPropertyList handle: 10a52, format: 0, depth: 0

D/MtpPropertyGroup( 7711): getPropertyList handle: 0x10a52, depth: 0x0, don't query if not necessary!!

D/ActivityThread(31097): ACT-AM_ON_PAUSE_CALLED ActivityRecord{29483b53 token=android.os.BinderProxy@b06bc90 {com.oppo.launcher/com.oppo.launcher.Launcher}}

D/MtpDatabase_JNI( 7711): virtual android::MtpResponseCode MyMtpDatabase::getObjectPropertyList(android::MtpObjectHandle, uint32_t, uint32_t, int, int, android::MtpDataPacket&): handle = 0x10a52, count = 1

I/MtpServer( 7711): sending data:

D/MtpDatabase_JNI( 7711): virtual android::MtpResponseCode MyMtpDatabase::getObjectPropertyList(android::MtpObjectHandle, uint32_t, uint32_t, int, int, android::MtpDataPacket&) result: 0x2001 

I/MtpServer( 7711): sending response 2001

W/ContextImpl(  900): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1456 com.android.server.am.OppoProtectEyeManagerService.sendProtectEyeBroadcast:167 com.android.server.am.OppoProtectEyeManagerService.handleProtectEyeMode:140 com.android.server.am.ActivityStack.resumeTopActivityInnerLocked:2151 com.android.server.am.ActivityStack.resumeTopActivityLocked:1723 

E/MtpServer( 7711): MtpServer::run mFD: 48

D/ViewRootImpl(  900): hardware acceleration is disabled, fakeHwAccelerated = true, HardwareRenderer.sRendererDisabled = false, forceHwAccelerated = false, HardwareRenderer.sSystemRendererDisabled = false, this = ViewRoot{18f83309 Starting ch.swissproductions.canora,ident = 343}

V/WindowManager(  900): Adding window Window{3e0e6f2f u0 Starting ch.swissproductions.canora} at 6 of 12 (after Window{1eb2b0d0 u0 com.android.settings/com.oppo.settings.SettingsActivity})

I/MtpServer( 7711): operation: MTP_OPERATION_GET_OBJECT_PROP_LIST, 0x9805

I/MtpServer( 7711): got MTP_OPERATION_GET_OBJECT_PROP_LIST command MTP_OPERATION_GET_OBJECT_PROP_LIST, line 602 

I/MtpServer( 7711): GetObjectPropList handle: 0x10a53, format: NONE, property: MTP_PROPERTY_OBJECT_FORMAT, group: 0, depth: 0

D/MtpDatabase( 7711): getObjectPropertyList: handle = 0x10a53, property = 0xdc02

D/MtpPropertyGroup( 7711): createProperty: code = 0xdc02, type = 0x4

D/MtpPropertyGroup( 7711): getPropertyList handle: 10a53, format: 0, depth: 0

D/MtpPropertyGroup( 7711): getPropertyList handle: 0x10a53, depth: 0x0, don't query if not necessary!!

D/MtpDatabase_JNI( 7711): virtual android::MtpResponseCode MyMtpDatabase::getObjectPropertyList(android::MtpObjectHandle, uint32_t, uint32_t, int, int, android::MtpDataPacket&): handle = 0x10a53, count = 1

D/MtpDatabase_JNI( 7711): virtual android::MtpResponseCode MyMtpDatabase::getObjectPropertyList(android::MtpObjectHandle, uint32_t, uint32_t, int, int, android::MtpDataPacket&) result: 0x2001 

I/MtpServer( 7711): sending data:

I/MtpServer( 7711): sending response 2001

E/MtpServer( 7711): MtpServer::run mFD: 48

I/BufferQueue(  169): [unnamed-169-3794](this:0xb5c57400,id:3794,api:0,p:-1,c:-1) BufferQueue core=(169:/system/bin/surfaceflinger)

I/BufferQueueConsumer(  169): [unnamed-169-3794](this:0xb5c57400,id:3794,api:0,p:-1,c:169) connect(C): consumer=(169:/system/bin/surfaceflinger) controlledByApp=false

I/BufferQueueConsumer(  169): [unnamed-169-3794](this:0xb5c57400,id:3794,api:0,p:-1,c:169) setConsumerName: unnamed-169-3794

I/BufferQueueConsumer(  169): [Starting ch.swissproductions.canora](this:0xb5c57400,id:3794,api:0,p:-1,c:169) setConsumerName: Starting ch.swissproductions.canora

I/BufferQueueConsumer(  169): [Starting ch.swissproductions.canora](this:0xb5c57400,id:3794,api:0,p:-1,c:169) setDefaultBufferSize: width=1 height=1

D/FeatureProxyBase(  900): FeatureProxyBase class constructor

D/FeatureProxyBase(  900): getService(), serviceName = multiwindow_service_v1

D/LockPatternUtils(  900): s=true ,L=true ,q=true ,v=false

D/KeyguardViewMediator(29576): setOccluded false

I/MtpServer( 7711): operation: MTP_OPERATION_GET_OBJECT_PROP_LIST, 0x9805

I/MtpServer( 7711): got MTP_OPERATION_GET_OBJECT_PROP_LIST command MTP_OPERATION_GET_OBJECT_PROP_LIST, line 602 

D/MtpDatabase( 7711): getObjectPropertyList: handle = 0x10a54, property = 0xdc02

I/MtpServer( 7711): GetObjectPropList handle: 0x10a54, format: NONE, property: MTP_PROPERTY_OBJECT_FORMAT, group: 0, depth: 0

D/MtpPropertyGroup( 7711): createProperty: code = 0xdc02, type = 0x4

D/MtpPropertyGroup( 7711): getPropertyList handle: 10a54, format: 0, depth: 0

D/MtpPropertyGroup( 7711): getPropertyList handle: 0x10a54, depth: 0x0, don't query if not necessary!!

D/MtpDatabase_JNI( 7711): virtual android::MtpResponseCode MyMtpDatabase::getObjectPropertyList(android::MtpObjectHandle, uint32_t, uint32_t, int, int, android::MtpDataPacket&): handle = 0x10a54, count = 1```

**Comment by muhammadarif1** [comment] 2019-05-27 18:33
i dont know if this a right log cat or not

**Comment by ZoidbergZero** [comment] 2019-05-27 18:35
You can upload and attach a file to a github comment by simple dragging and dropping the file onto your comment.

Please record a Logcat of a full session of you Opening the App and it crashing, and attach it here to a comment

**Comment by muhammadarif1** [comment] 2019-05-27 18:37
[canora.txt](https://github.com/ZoidbergZero/Canora-MusicPlayer/files/3224741/canora.txt)

**Comment by ZoidbergZero** [comment] 2019-05-27 18:49
Are you using the Latest Version 0.41?

**Comment by ZoidbergZero** [comment] 2019-05-27 19:01
Please supply me the Correct Android Version(You can find your android version in the Settings under Info) 
theres no Android 6.1, and your Device is shown to be using Android 4.4.2 after a quick google search.

**Comment by muhammadarif1** [comment] 2019-05-27 19:02
my android 5.1
i type wrong number before. and i try a new version of canora and a bug still appear
here a new log
[canora2.txt](https://github.com/ZoidbergZero/Canora-MusicPlayer/files/3224788/canora2.txt)

**Comment by ZoidbergZero** [comment] 2019-05-27 19:14
Please try Version 0.42 and tell me the Results

**Comment by muhammadarif1** [comment] 2019-05-27 19:30
sorry to say but the bug still appear

**Comment by ZoidbergZero** [comment] 2019-05-27 19:39
Please try [this](https://github.com/ZoidbergZero/Canora-MusicPlayer/files/3224833/app-debug.zip) build which doesnt load any files and post the logcat.

**Comment by muhammadarif1** [comment] 2019-05-27 20:13
i try debug app and i can't install

**Comment by muhammadarif1** [comment] 2019-05-27 20:14
let me try on another device

**Comment by ZoidbergZero** [comment] 2019-05-27 20:44
You need to unzip the File first to install it, as github doesnt allow apk uploads i had to upload it as zip.

**Comment by muhammadarif1** [comment] 2019-05-28 00:00
I now how to unzip man, i am not stupid

**Comment by muhammadarif1** [comment] 2019-05-28 00:02
![Screenshot_2019-05-28-07-01-40-71](https://user-images.githubusercontent.com/36690337/58442599-86a90c00-8116-11e9-8fbd-b60bc1363c68.png)

**Comment by ZoidbergZero** [comment] 2019-05-28 08:08
Ohh oops thats a Error on my Part, [this](https://github.com/ZoidbergZero/Canora-MusicPlayer/files/3226243/app-debug.zip) build should install.

**Comment by muhammadarif1** [comment] 2019-05-28 14:08
Are this app still in alpha stage?

**Comment by ZoidbergZero** [comment] 2019-05-28 16:53
Yes the App is still in development, did the Testbuild i posted worked without the app crashing? That build is just a Test that doesnt load any Files to see if the App is maybe Doing too much Work on the UI Thread and thus Crashing.

**Comment by ZoidbergZero** [comment] 2019-05-30 21:09
Closing the Issue as you arent Providing further Information and the Logcats dont indicate a Problem i could Fix.

**Closed by ZoidbergZero** 2019-05-30 21:09 UTC
Labels: bug
